# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 8 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: zeta

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: MAIN

description: Stylish Jekyll Theme
author:
  name: zeta
  email: shail1027@skuniv.ac.kr
  github: shail1027
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: 기록하지 않으면 기억되지 않는다.
  # email_md5: f77b5e8e070b0b85894c78a7c6059f24

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
