backend:
  name: github
  repo: shail1027/shail1027.github.io
  branch: main
  base_url: https://decap-proxy.yi838953.workers.dev

media_folder: "assets/img/posts"
public_folder: "/assets/img/posts"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: false
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
